name: tag-master-branch
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1

      - uses: aarnott/nbgv@master
        with:
          setAllVars: true
      - run: echo "VERSION= $NBGV_Version"
      
      - name: Chmod shell script
        run: chmod +x ./version.sh
        shell: bash
        continue-on-error: true

      - name: Version
        run: ./version.sh
        shell: bash
