name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301     
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    - name: Build Library
      run: dotnet build cbosTestLibaray1.csproj --configuration Release
    
    - name: Create Nuget Package
      run: dotnet pack cbosTestLibaray1.csproj --configuration Release
      

        
